version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  superset:
    image: amancevice/superset
    restart: always
    depends_on:
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SUPERSET_HOME: /etc/superset
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
      - sqlite:/var/lib/superset
  jupyter:
    image: jupyter/base-notebook
    restart: always
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - sqlite:/home/jovyan
volumes:
  redis:
    external: false
  sqlite:
    driver_opts:
      type: none
      device: ${PWD}/superset #NOTE needs full path (~ doesn't work)
      o: bind
